name: PicosPacos
description: The ultimate item utility system
version: ${version}
main: com.saicone.picospacos.PicosPacos
authors: [Rubenicos]
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - DeluxeCombat