# The event ID
example-event:
  # Event types:
  # PLAYER_JOIN    = Player join server
  # PLAYER_LEAVE   = Player leave server
  # PLAYER_RESPAWN = Player respawn
  # PLAYER_DIES    = Player dies
  # PLAYER_WORLD   = Player change world
  # ITEM_DROP      = Item being drop
  # ITEM_PICKUP    = Item being pickup
  # ITEM_CLICK     = Item is clicked on inventory
  when: PLAYER_DIES
  # Event priorities:
  # - LOWEST = First to be executed
  # - LOW
  # - NORMAL
  # - HIGH
  # - HIGHEST
  # - MONITOR = Last to be executed
  priority: MONITOR
  # Delay to check items
  delay: 0
  # Filter item to detect
  item:
    material: 'contains=SWORD'
    amount: '<60'
    name:
      - 'contains=Thunder'
      - 'contains=thunder'
    lore(contains):
      - '&7This item can''t be'
      - '&7lose on death!'
  # Action types:
  # RESTORE = Return the item when player respawn or joins
  # SAVE    = Save the item to be claimed with /lostitems (Configure it on setting.yml)
  # TAKE    = Confiscate item from player
  # DELETE  = Delete item from existence
  # CANCEL  = Cancel the event from being executed
  # COMMAND = Execute a console command
  run:
    - 'restore'
    - 'command: msg %player_name% Hey! You almost lost the thunder sword!'

protected-lore:
  when: ITEM_DROP
  item:
    lore(any): 'contains=PROTECTED ITEM'
  run:
    - 'cancel'