# The script ID
example-script:
  # Enable or not this script (true by default)
  enabled: false
  # Filter item to detect
  item:
    material: 'contains=SWORD'
    amount: '<60'
    name:
      - 'contains=Thunder'
      - 'contains=thunder'
    lore(contains):
      - '&7This item can''t be'
      - '&7lose on death!'
  # Event types:
  # PLAYER_JOIN    = Player join server
  # PLAYER_LEAVE   = Player leave server
  # PLAYER_RESPAWN = Player respawn
  # PLAYER_DIES    = Player dies
  # PLAYER_WORLD   = Player change world
  # ITEM_DROP      = Item being drop
  # ITEM_PICKUP    = Item being pickup
  # ITEM_CLICK     = Item is clicked on inventory
  #
  # Action types:
  # RESTORE = Return the item when player respawn or joins
  # SAVE    = Save the item to be claimed with /lostitems (Configure it on setting.yml)
  # TAKE    = Confiscate item from player
  # DELETE  = Delete item from existence
  # CANCEL  = Cancel the event from being executed
  # COMMAND = Execute a console command (for example "command: broadcast HELLO EVERYONE!")
  # LANG    = Send a lang message by its path (for example "lang: script.drop-message")
  # DELAY   = Delay the execution (for example "delay: 5 seconds")
  when:
    PLAYER_DIES:
      - 'restore'
      - 'command: msg %player_name% Hey! You almost lost the thunder sword!'

protected-lore:
  enabled: false
  item:
    lore(any): 'contains=PROTECTED ITEM'
  when:
    ITEM_DROP:
      - 'cancel'

illegal-item:
  enabled: false
  item:
    material: BEDROCK
    name: '&c&lSUPER BEDROCK'
  when:
    PLAYER_JOIN:
      # Delay to check items
      delay: 5 seconds
      actions:
        - 'delete'
        - 'delay: 1 second' # The items should be deleted first on join, and then run the command
        - 'command: ban %player_name% Illegal item detected'
    ITEM_DROP,ITEM_CLICK:
      - 'delete'
      - 'command: ban %player_name% Illegal item detected'
